language: python
python:
  - 3.9

services:
  - mysql

env:
  - MYSQL_USER=flask-user
  - MYSQL_PASSWORD=root
  - MYSQL_SERVER=127.0.0.1:3306
  - MYSQL_DATABASE=Cinemate

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS Cinemate;'

install:
  - pip install -r requirements.txt

script:
  - pylint cinemate_app
  - coverage run -m unittest discover cinemate_app/tests
  - coverage report

after_success:
  - coveralls
