"""Test migration

Revision ID: 0990ba61e165
Revises: 
Create Date: 2023-03-01 16:10:46.369881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0990ba61e165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=70), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('movie')
    # ### end Alembic commands ###
